"""The top bar's look: separate "islands" in the wallpaper's colours, in nine styles to choose from
(`wallrice bar`). Each style is defined once here and used both to generate the GNOME Shell
stylesheet (the wallrice extension loads it, and reloads it live on every change) and to draw the
previews in the chooser and the picker."""
import math
import time
from dataclasses import dataclass

from .color import mix


@dataclass(frozen=True)
class BarStyle:
    id: str
    name: str
    border: str = "all"     # all | sides | bottom | none
    width: float = 1.6      # border width (px)
    radius: float = 10      # corner radius (px); 99 = pill
    alpha: float = 0.92     # island background opacity
    glow: bool = False      # a soft accent glow around each island
    tint: float = 0.0       # island background mixed toward the accent
    floating: bool = False  # one floating bar behind the islands
    fill_clock: bool = False


STYLES = [
    BarStyle("outlined", "Outlined islands"),
    BarStyle("sidebars", "Accent side bars", border="sides", width=3, radius=8),
    BarStyle("glow", "Thin outline + glow", width=1, alpha=0.88, glow=True),
    BarStyle("pills", "Pills", radius=99),
    BarStyle("underline", "Accent underline", border="bottom", width=2.5, radius=6, alpha=0.9),
    BarStyle("glass", "Glass", width=1, radius=12, alpha=0.55),
    BarStyle("tinted", "Tinted, no border", border="none", width=0, alpha=0.95, tint=0.18),
    BarStyle("floating", "One floating bar", width=1.2, radius=9, alpha=0.95, floating=True),
    BarStyle("filled", "Filled clock", fill_clock=True),
]
DEFAULT = "outlined"
BY_ID = {s.id: s for s in STYLES}


def get(style_id):
    """A style by id or by number (1-9); the default for anything else."""
    if isinstance(style_id, str) and style_id.isdigit():
        n = int(style_id)
        return STYLES[n - 1] if 1 <= n <= len(STYLES) else BY_ID[DEFAULT]
    return BY_ID.get(style_id or DEFAULT, BY_ID[DEFAULT])


def rgba(c, a=1.0):
    r, g, b = (round(max(0, min(1, x)) * 255) for x in c)
    return f"rgba({r}, {g}, {b}, {a:.2f})"


def island_bg(style, th):
    return mix(th["surface"], th["accent"], style.tint)


# ---------------------------------------------------------------- GNOME Shell stylesheet

def shell_css(th, style, dock=True):
    """The stylesheet the wallrice extension loads. Every rule is scoped to classes the extension adds,
    so with the extension off nothing changes."""
    acc, fg, bg, on = th["accent"], th["fg"], th["bg"], th["on_accent"]
    base = island_bg(style, th)
    hover = mix(base, acc, 0.28)
    w = style.width
    border = {
        "all": f"border: {w}px solid {rgba(acc)};",
        "sides": f"border: 0; border-left: {w}px solid {rgba(acc)}; border-right: {w}px solid {rgba(acc)};",
        "bottom": f"border: 0; border-bottom: {w}px solid {rgba(acc)};",
        "none": "border: 0;",
    }[style.border]
    glow = f"box-shadow: 0 0 6px 1px {rgba(acc, 0.45)};" if style.glow else "box-shadow: none;"
    radius = min(style.radius, 17)
    P = "#panel.wallrice-panel"
    css = [f"/* Generated by wallrice ({style.id}) from the current wallpaper. Edits are overwritten. */",
           f"{P} {{ background-color: {rgba(bg, 0.82) if style.floating else 'transparent'}; height: 40px;"
           f" {'border-radius: 14px; margin: 4px 8px 0 8px;' if style.floating else ''} }}",
           f"{P} .panel-corner {{ -panel-corner-opacity: 0; }}",
           f"{P} .panel-button {{ background-color: {rgba(base, style.alpha)}; color: {rgba(fg)}; {border}"
           f" border-radius: {radius}px; margin: 4px 3px; padding: 0 10px; {glow}"
           f" -natural-hpadding: 10px; -minimum-hpadding: 6px; transition-duration: 160ms; }}",
           f"{P} .panel-button:hover {{ background-color: {rgba(hover, max(style.alpha, 0.9))}; color: {rgba(fg)}; }}",
           f"{P} .panel-button:active, {P} .panel-button:checked, {P} .panel-button:focus,"
           f" {P} .panel-button:overview {{ background-color: {rgba(acc)}; color: {rgba(on)}; box-shadow: none; }}",
           f"{P} .panel-button .system-status-icon, {P} .panel-button StIcon {{ color: {rgba(fg)}; }}",
           f"{P} .panel-button:active StIcon, {P} .panel-button:checked StIcon {{ color: {rgba(on)}; }}",
           f"{P} .panel-button.clock-display, {P} .clock {{ color: {rgba(fg)}; }}",
           # workspaces 1-4
           ".wallrice-ws { spacing: 4px; }",
           f".wallrice-ws-dot {{ min-width: 24px; height: 24px; border-radius: 12px; color: {rgba(fg)};"
           f" font-weight: normal; text-align: center; }}",
           f".wallrice-ws-dot:hover {{ background-color: {rgba(hover)}; }}",
           f".wallrice-ws-dot.active {{ background-color: {rgba(acc)}; color: {rgba(on)}; font-weight: bold; }}",
           ".wallrice-ws-dot.busy { text-decoration: underline; }",
           ".wallrice-launchers { spacing: 10px; }",
           f".wallrice-launcher StIcon {{ icon-size: 16px; color: {rgba(fg)}; }}",
           f".wallrice-launcher:hover StIcon {{ color: {rgba(acc)}; }}",
           f".wallrice-title {{ color: {rgba(fg)}; font-weight: normal; }}",
           f".wallrice-stats-key {{ color: {rgba(acc)}; font-weight: bold; }}",
           f".wallrice-stats-value {{ color: {rgba(fg)}; padding-right: 8px; }}",
           ".wallrice-bell StIcon { icon-size: 16px; }",
           f".wallrice-bell.unread StIcon {{ color: {rgba(acc)}; }}"]
    if style.fill_clock:
        css.append(f"{P} .panel-button.wallrice-clock {{ background-color: {rgba(acc)}; color: {rgba(on)}; font-weight: bold; }}")
        css.append(f"{P} .panel-button.wallrice-clock .clock {{ color: {rgba(on)}; }}")
    if dock:  # Dash to Dock / Ubuntu Dock: a floating rounded dock in the theme's colours
        css += [f"#dashtodockContainer.wallrice-dock .dash-background {{ background-color: {rgba(bg, 0.9)};"
                f" border: 1px solid {rgba(acc, 0.55)}; border-radius: 18px; }}",
                f"#dashtodockContainer.wallrice-dock .app-well-app:hover .overview-icon,"
                f" #dashtodockContainer.wallrice-dock .show-apps:hover .overview-icon"
                f" {{ background-color: {rgba(mix(bg, acc, 0.3), 0.9)}; }}",
                f"#dashtodockContainer.wallrice-dock .app-well-app-running-dot {{ background-color: {rgba(acc)}; }}"]
    # notifications and menus follow too
    css += [f".wallrice-panel-menus .popup-menu-content, .wallrice-panel-menus .quick-settings"
            f" {{ border: 1px solid {rgba(acc, 0.6)}; }}"]
    return "\n".join(css) + "\n"


# ---------------------------------------------------------------- previews (cairo)

def draw_bar(cr, th, style, W, a=1.0, text=None, now=None, title="Terminal", scale=1.0):
    """The top bar as the extension makes it, at real size across a W-wide screen (cairo context at
    the screen's top-left). `text(cr, s, x, y, size, color, alpha, weight, align=...)` draws a label."""
    from .ui.common import rrect
    acc, fg, bg, on = th["accent"], th["fg"], th["bg"], th["on_accent"]
    base = island_bg(style, th)
    H = 32 * scale
    y0 = 4 * scale
    fs = 13 * scale
    cr.save()
    if style.floating:
        rrect(cr, 8 * scale, 2 * scale, W - 16 * scale, H + 4 * scale, 14 * scale)
        cr.set_source_rgba(*bg, 0.82 * a)
        cr.fill()

    def island(x, w, filled=False):
        r = min(style.radius, 17) * scale
        if style.glow:
            for k in range(4):
                rrect(cr, x - k * 1.5, y0 - k * 1.5, w + k * 3, H + k * 3, r + k * 1.5)
                cr.set_source_rgba(*acc, 0.10 * a)
                cr.fill()
        rrect(cr, x, y0, w, H, r)
        cr.set_source_rgba(*(acc if filled else base), a * (1 if filled else style.alpha))
        cr.fill()
        bw = style.width * scale
        cr.set_source_rgba(*acc, a)
        if style.border == "all":
            rrect(cr, x + bw / 2, y0 + bw / 2, w - bw, H - bw, r)
            cr.set_line_width(bw)
            cr.stroke()
        elif style.border in ("sides", "bottom"):
            cr.save()
            rrect(cr, x, y0, w, H, r)
            cr.clip()
            if style.border == "sides":
                cr.rectangle(x, y0, bw, H)
                cr.rectangle(x + w - bw, y0, bw, H)
            else:
                cr.rectangle(x, y0 + H - bw, w, bw)
            cr.fill()
            cr.restore()

    def label(s, x, col, weight="", align="left"):
        if text:
            return text(cr, s, x, y0 + H / 2 - fs * 0.62, fs, col, a, weight, align=align)
        return (len(s) * fs * 0.55, fs)

    s = scale
    x = 12 * s  # workspaces 1-4
    island(x, 116 * s)
    for k in range(4):
        cx = x + 20 * s + k * 26 * s
        if k == 0:
            cr.arc(cx, y0 + H / 2, 11 * s, 0, 2 * math.pi)
            cr.set_source_rgba(*acc, a)
            cr.fill()
            label("1", cx, on, "Bold", "center")
        else:
            label(str(k + 1), cx, fg, align="center")
    x = 134 * s  # launchers
    island(x, 112 * s)
    for k in range(4):
        rrect(cr, x + 14 * s + k * 23 * s, y0 + H / 2 - 7 * s, 14 * s, 14 * s, 3 * s)
        cr.set_source_rgba(*fg, 0.9 * a)
        cr.fill()
    tw = max(160 * s, label(title, -1e4, fg)[0] + 40 * s)  # the focused window's title
    island(W / 2 - tw / 2, tw)
    label(title, W / 2, fg, align="center")
    right = W - 12 * s  # from the right: bell, clock, system, stats
    island(right - 46 * s, 46 * s)
    bx = right - 23 * s
    cr.arc(bx, y0 + H / 2 - 1 * s, 6 * s, math.pi, 2 * math.pi)
    cr.line_to(bx + 6 * s, y0 + H / 2 + 5 * s)
    cr.line_to(bx - 6 * s, y0 + H / 2 + 5 * s)
    cr.close_path()
    cr.set_source_rgba(*fg, a)
    cr.fill()
    clock = time.strftime("%a %d %b  %H:%M", time.localtime(now)) if now else "Sun 4 Oct  21:40"
    cw = 140 * s
    island(right - 52 * s - cw, cw, filled=style.fill_clock)
    label(clock, right - 52 * s - cw / 2, on if style.fill_clock else fg, "Bold" if style.fill_clock else "", "center")
    sx = right - 58 * s - cw - 96 * s
    island(sx, 90 * s)
    for k in range(3):
        cr.arc(sx + 22 * s + k * 23 * s, y0 + H / 2, 5.5 * s, 0, 2 * math.pi)
        cr.set_source_rgba(*fg, 0.92 * a)
        cr.fill()
    vx = sx - 6 * s - 196 * s
    island(vx, 196 * s)
    xx = vx + 12 * s
    for key, val in (("cpu", "9%"), ("mem", "3.1G"), ("net", "12K")):
        w1, _ = label(key, xx, acc, "Bold")
        w2, _ = label(val, xx + w1 + 4 * s, fg)
        xx += w1 + w2 + 14 * s
    cr.restore()
    return H + y0


def describe(style):
    return f"{STYLES.index(style) + 1}  {style.name}"
