"""Renderers: pure functions from a theme to file contents ({path: text}). They only read; the engine
writes everything once every renderer has succeeded, so a failure never leaves the desktop half-themed."""
import os
from pathlib import Path

from .. import paths


def data_dirs():
    """$XDG_DATA_HOME first, then $XDG_DATA_DIRS (where themes and icons live)."""
    dirs = [paths.data_home()]
    for d in (os.environ.get("XDG_DATA_DIRS") or "/usr/local/share:/usr/share").split(":"):
        if d and Path(d) not in dirs:
            dirs.append(Path(d))
    return dirs


def find_dir(kind, name):
    """A theme ("themes") or icon theme ("icons") by name, user dirs first."""
    for base in [paths.home() / (".themes" if kind == "themes" else ".icons"), *(d / kind for d in data_dirs())]:
        if (base / name).is_dir():
            return base / name
    return None


HEADER = "Generated by wallrice from the current wallpaper. Edits are overwritten."
